service: dlq-watcher

frameworkVersion: ">=1.21.1 <2.0.0"

custom:
  defaultStage: dev
  environment: ${file(./env.yml)}

provider:
  name: aws
  runtime: nodejs6.10
  profile: default
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: "*"

package:
  exclude:
    - coverage/**
    - test/**

functions:
  watch:
    handler: handler.watch
    description: Monitor Dead Letter Queue.
    memorySize: 128
    timeout: 30
    environment: ${self:custom.environment.${self:provider.stage}}
    events:
      - schedule: cron(0/1 * * * ? *)

resources:
  Resources:
    WatchLogGroup:
      Properties:
        RetentionInDays: "30"
